dev
Katibat/Playlist-Maker pull request #14
Opened 2023-12-10 17:04 UTC by Katibat

2023-12-12 11:26 UTC, Anna-Malinina requested changes

2023-12-12 11:26 UTC, Anna-Malinina commented on .idea/deploymentTargetDropDown.xml
Лучше добавить всю директорию .idea в [гитигнор](https://www.atlassian.com/ru/git/tutorials/saving-changes/gitignore), чтобы такие файлы не проскальзывали, так как они относятся конкретно к твоей иде

2023-12-12 11:26 UTC, Anna-Malinina commented on app/src/main/java/com/example/playlistmaker/search/data/SearchRepositoryImpl.kt
> +                emit(Resource.Error("Проверьте подключение к интернету"))
Это считается за хардкод текст. Если бы приложение поддерживало больше языков, то невозможно было бы перевести корректно этот код без костылей. Хорошим вариантом решения проблемы - прокидывать только тип ошибки (для этого надо завести разные для ошибки с интернетом и ошибкой сервера), по которому уже в UI слое будет вытаскиваться нужный текст из ресурсов. Тогда останется возможность для перевода

2023-12-12 11:26 UTC, Anna-Malinina commented on app/src/main/java/com/example/playlistmaker/search/domain/impl/SearchInteractorImpl.kt
> +                is Resource.Success<*> -> {
Здесь необязательно писать wildcard <*>, будет работать и без них

2023-12-18 07:02 UTC, Anna-Malinina commented on app/src/main/java/com/example/playlistmaker/player/data/PlayerRepositoryImpl.kt
> +    private var mediaPlayer: MediaPlayer = MediaPlayer()
Это является нарушением условия DI из 17 спринта: "Никакие экземпляры классов не создаются внутри зависимых компонентов."

2023-12-18 07:02 UTC, Anna-Malinina commented on app/src/main/java/com/example/playlistmaker/player/ui/PlayerActivity.kt
> +            binding?.ivPlayTrack?.setOnClickListener {
Так как установка листенера происходит внутри observe, то он становится "одноразовым". То есть при каждом изменение стейта мы присваиваем новый листенер. Это не очень хорошо с точки зрения производительности и оптимизации

2023-12-30 07:00 UTC, Katibat commented on app/src/main/java/com/example/playlistmaker/player/ui/PlayerActivity.kt
> +            binding?.ivPlayTrack?.setOnClickListener {
Исправлено.

2023-12-30 07:00 UTC, Katibat commented on app/src/main/java/com/example/playlistmaker/player/data/PlayerRepositoryImpl.kt
> +    private var mediaPlayer: MediaPlayer = MediaPlayer()
Исправлено.

2023-12-30 07:00 UTC, Katibat commented on app/src/main/java/com/example/playlistmaker/search/domain/impl/SearchInteractorImpl.kt
> +                is Resource.Success<*> -> {
Исправлено.

2023-12-30 07:08 UTC, Katibat commented on app/src/main/java/com/example/playlistmaker/search/data/SearchRepositoryImpl.kt
> +                emit(Resource.Error("Проверьте подключение к интернету"))
Это часть из теории, исправила!

2023-12-30 07:08 UTC, Katibat commented on .idea/deploymentTargetDropDown.xml
Добавила!

2023-12-30 07:17 UTC, Katibat commented
Добрый день!
Спасибо за возможность доработать код без академа! Просто исправить таймер не удалось, откатила плеер до предыдущего спринта, код он работал и многочисленными проверками, вооружившись схемой lifecycle activity, исправила баги. Надеюсь ничего не упустила.

2024-01-02 11:37 UTC, merged